{% set version = "1.5.0" %}

package:
  name: xcube
  version: {{ version }}

source:
  url: https://github.com/dcs4cop/xcube/archive/v{{ version }}.tar.gz
  sha256: 53303d39b78b57a6859ecd25b4bb6aa50edacb7eda7c1059ac52aa7847683fdf

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv
  entry_points:
    - xcube = xcube.cli.main:main

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
  # Required
    - adlfs >=2023.1
    - affine >=2.2
    - click >=8.0
    - cmocean >=2.0
    - dask >=2021.6
    - dask-image >=0.6
    - deprecated >=1.2
    - distributed >=2021.6
    - fiona >=1.8
    - fontconfig
    - fsspec >=2021.6
    - gdal >=3.0
    - geopandas >=0.8
    - jdcal >=1.4
    - jsonschema >=3.2
    - lz4
    - mashumaro
    - matplotlib-base >=3.0
    - netcdf4 >=1.5
    - numba >=0.52
    - numpy >=1.16
    - openssl
    - pandas >=1.3
    - pillow >=6.0
    - pyjwt >=1.7
    - pyproj >=3.0
    - python-blosc
    - pyyaml >=5.4
    - rasterio >=1.2
    - requests >=2.25
    - requests-oauthlib >=1.3
    - rfc3339-validator >=0.1
    - rioxarray >=0.11
    - s3fs >=2021.6
    - scipy >=1.6.0
    - setuptools >=41.0
    - shapely >=1.6
    - tornado >=6.0
    - urllib3 >=1.26
    - werkzeug
    - xarray >=2022.6
    - zarr >=2.11
test:
  imports:
    - xcube
    - xcube.cli.main
  commands:
    - xcube --help

about:
  summary: xcube is a Python package for generating and exploiting data cubes powered by xarray, dask, and zarr
  home: https://github.com/dcs4cop/xcube
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: xcube is a Python package for generating and exploiting data cubes powered by xarray, dask, and zarr. It has been designed in the context of Earth Observation data.
  doc_url: https://xcube.readthedocs.io
  dev_url: https://github.com/dcs4cop/xcube

extra:
  recipe-maintainers:
    - AliceBalfanz
    - TejasMorbagal
    - forman
    - pont-us
    - thomasstorm
    - TonioF
    - ruchimotwaniBC
